# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fft_filter_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FFTConvolutionDialogBase(object):
    def setupUi(self, FFTConvolutionDialogBase):
        FFTConvolutionDialogBase.setObjectName("FFTConvolutionDialogBase")
        FFTConvolutionDialogBase.resize(347, 360)
        self.formLayout = QtWidgets.QFormLayout(FFTConvolutionDialogBase)
        self.formLayout.setObjectName("formLayout")
        self.input_label = QtWidgets.QLabel(FFTConvolutionDialogBase)
        self.input_label.setObjectName("input_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.input_label)
        self.input_layer = QgsMapLayerComboBox(FFTConvolutionDialogBase)
        self.input_layer.setObjectName("input_layer")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_layer)
        self.output_label = QtWidgets.QLabel(FFTConvolutionDialogBase)
        self.output_label.setObjectName("output_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.output_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.output_file = QtWidgets.QLineEdit(FFTConvolutionDialogBase)
        self.output_file.setObjectName("output_file")
        self.horizontalLayout.addWidget(self.output_file)
        self.output_file_button = QtWidgets.QPushButton(FFTConvolutionDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.output_file_button.sizePolicy().hasHeightForWidth())
        self.output_file_button.setSizePolicy(sizePolicy)
        self.output_file_button.setObjectName("output_file_button")
        self.horizontalLayout.addWidget(self.output_file_button)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.size_label = QtWidgets.QLabel(FFTConvolutionDialogBase)
        self.size_label.setObjectName("size_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.size_label)
        self.size = QtWidgets.QLineEdit(FFTConvolutionDialogBase)
        self.size.setPlaceholderText("")
        self.size.setObjectName("size")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.size)
        self.line = QtWidgets.QFrame(FFTConvolutionDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.line)
        self.optional = QtWidgets.QLabel(FFTConvolutionDialogBase)
        self.optional.setObjectName("optional")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.optional)
        self.window = QtWidgets.QCheckBox(FFTConvolutionDialogBase)
        self.window.setEnabled(True)
        self.window.setObjectName("window")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.window)
        self.rowlabel = QtWidgets.QLabel(FFTConvolutionDialogBase)
        self.rowlabel.setObjectName("rowlabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.rowlabel)
        self.window_rows = QtWidgets.QLineEdit(FFTConvolutionDialogBase)
        self.window_rows.setEnabled(False)
        self.window_rows.setObjectName("window_rows")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.window_rows)
        self.collabel = QtWidgets.QLabel(FFTConvolutionDialogBase)
        self.collabel.setObjectName("collabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.collabel)
        self.window_cols = QtWidgets.QLineEdit(FFTConvolutionDialogBase)
        self.window_cols.setEnabled(False)
        self.window_cols.setObjectName("window_cols")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.window_cols)
        self.line_2 = QtWidgets.QFrame(FFTConvolutionDialogBase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.line_2)
        self.check_add = QtWidgets.QCheckBox(FFTConvolutionDialogBase)
        self.check_add.setChecked(True)
        self.check_add.setObjectName("check_add")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.check_add)
        self.button_box = QtWidgets.QDialogButtonBox(FFTConvolutionDialogBase)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.button_box)

        self.retranslateUi(FFTConvolutionDialogBase)
        self.button_box.accepted.connect(FFTConvolutionDialogBase.accept)
        self.button_box.rejected.connect(FFTConvolutionDialogBase.reject)
        self.window.toggled['bool'].connect(self.window_rows.setEnabled)
        self.window.toggled['bool'].connect(self.window_cols.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(FFTConvolutionDialogBase)

    def retranslateUi(self, FFTConvolutionDialogBase):
        _translate = QtCore.QCoreApplication.translate
        FFTConvolutionDialogBase.setWindowTitle(_translate("FFTConvolutionDialogBase", "FFT COnvolution Filters"))
        self.input_label.setText(_translate("FFTConvolutionDialogBase", "Input Layer"))
        self.output_label.setText(_translate("FFTConvolutionDialogBase", "Output File"))
        self.output_file_button.setText(_translate("FFTConvolutionDialogBase", "..."))
        self.size_label.setText(_translate("FFTConvolutionDialogBase", "Smoothing radius (pixels)"))
        self.size.setText(_translate("FFTConvolutionDialogBase", "10"))
        self.optional.setText(_translate("FFTConvolutionDialogBase", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic;\">Optional</span></p></body></html>"))
        self.window.setText(_translate("FFTConvolutionDialogBase", "Apply windowed algorithm"))
        self.rowlabel.setText(_translate("FFTConvolutionDialogBase", "Window Rows"))
        self.collabel.setText(_translate("FFTConvolutionDialogBase", "Window Columns"))
        self.check_add.setText(_translate("FFTConvolutionDialogBase", "Add Output Layer to Map Canvas"))

from qgis.gui import QgsMapLayerComboBox
